name: Release

on:
  release:
    types:
      - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/${{ vars.NUGET_GLOBAL_PACKAGES_FOLDER }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: ${{ vars.DOTNET_SDK_VERSIONS }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore
        run: dotnet restore --locked-mode
      - name: Release Build & Pack
        run: dotnet pack ./src/Nogic.JsonConverters/Nogic.JsonConverters.csproj -c Release --no-restore --output nupkgs -p:Version=${TAG_VERSION:1}
        env:
          TAG_VERSION: ${{ github.event.release.tag_name }} # v0.0.0-abc

      - name: Publish to NuGet
        run: dotnet nuget push "nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: packages
          path: nupkgs/
